title: Республиканский Перинатальный Центр
description: Сайт Перинатального Центра г. Петрозаводска
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  posts:
    output: true
