defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: people
    values:
      layout: person
collections:
  structure:
    output: true
  posts:
    output: true
  people:
    output: true

excerpt_separator: <!--more-->

paginate: 5
paginate_path: "/news/page:num/"
permalink: "/news/:year/:month/:day/:title.html"

author: rpc

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compact

# https://tech.yandex.ru/speechkit/cloud/doc/guide/common/speechkit-common-tts-http-request-docpage/
yandex:
  speechkit:
    id: 8e7ac46b-c6aa-45e1-951d-b38035884660
    format: mp3
    quality: lo
    lang: ru-RU
    speaker: omazh
    emotion: good



