title: Республиканский Перинатальный Центр
description: Сайт Перинатального Центра г. Петрозаводска
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
