---
new_page_extension: md
auto_deploy: false
admin_path: "/mngr"
webhook_url: 
sections:
- type: directory
  path: _people
  label: People
  create: all
  match: "**/*"
- type: directory
  path: _structure
  label: Structure
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - posts
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - default
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
