---
new_page_extension: md
auto_deploy: false
admin_path: "/mngr"
webhook_url: 
sections:
- type: directory
  path: _posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - test
  - b3873f39-697e-492f-9ce6-64a7b24a0849
- type: directory
  path: _people
  label: People
  create: all
  match: "**/*"
- type: directory
  path: _structure
  label: Structure
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - posts
- type: document
  path: _data/information.yml
  label: Information
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
